### ISSUE TITLE
[FEATURE] 루트 컴포넌트 header

### ISSUE THREAD

**Issue by Yejin-Han** [qhqo0403/sonane-book#11]
### ✏ISSUE

루트 컴포넌트 header

### 📝Description

루트 컴포넌트인 header를 생성하고 페이지 구조를 위해 간단한 스타일링을 함.

**Comment by qhqo0403** [comment]
Branch [_Feat_Function/issue-11](https://github.com/qhqo0403/sonane-book/tree/_Feat_Function/issue-11) created!
