### ISSUE TITLE
[FEATURE] tailwind 기본 설정

### ISSUE THREAD

**Issue by Yejin-Han** [qhqo0403/sonane-book#18]
### ✏ISSUE

tailwind 기본 설정

### 📝Description

기본 설정을 하지 않으면 tailwind CSS 사용이 불가능하므로 설정해준다.

### ✅To do
- [ ] tailwind.config.js 설정
- [ ] index.css에 적용
- [ ] 되는지 확인

**Comment by qhqo0403** [comment]
Branch [_Feat_Function/issue-18](https://github.com/qhqo0403/sonane-book/tree/_Feat_Function/issue-18) created!
