### ISSUE TITLE
[BUG] Merge 오류로 인한 파일 충돌 해결 및 과거 파일 삭제

### ISSUE THREAD

**Issue by Yejin-Han** [qhqo0403/sonane-book#22]
### 🐞Bug

Merge 오류로 인한 파일 충돌 해결 및 과거 파일 삭제

### 📄Description

새로운 브랜치에서 작업 시 main에서 merge한 것이 아니라 브랜치에서 바로 새 브랜치로 squashed merge 해 오면서 과거 파일이 다 살아나서 충돌 문제 발생 

### 🗝Solution

- solution 1) Merge 충돌 난 파일 수정 (Home.js)
- solution 2) Root.css 삭제

**Comment by qhqo0403** [comment]
Branch [_Bug_Function/issue-22](https://github.com/qhqo0403/sonane-book/tree/_Bug_Function/issue-22) created!
